version: 2.1

orbs:
  node: circleci/node@7.0.0

parameters:
  node_version:
    type: string
    default: '22.13.0'

commands:
  install_deps:
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - node/install-packages:
          pkg-manager: pnpm
          cache-only-lockfile: true
      - node/install:
          install-pnpm: true
          pnpm-version: 9.15.4

jobs:
  build:
    executor:
      name: node/default
      tag: << pipeline.parameters.node_version >>
    working_directory: ~/repo
    steps:
      - checkout
      - install_deps
      - run: yarn build
      - run: yarn test
      - run: yarn test:repl
      - run: yarn lint:ci
      - run: yarn type-check

workflows:
  build_test:
    jobs:
      - build
